name: terminus
favicon: null
layout_spectrum: 0.0987300246488303
typography_spectrum: 0.23226751084439456
title: The Borderlands
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.005396632943302393
  lightness: 0.4895914576482028
  saturation: 0.06481892755255103
  rhythmicContrast: 0.301407671533525
purpose: []
